# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='voting.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.Option')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.Record')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting.Poll'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('record', 'option')]),
        ),
        migrations.AlterOrderWithRespectTo(
            name='record',
            order_with_respect_to='poll',
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set([('poll', 'title')]),
        ),
        migrations.AlterOrderWithRespectTo(
            name='option',
            order_with_respect_to='poll',
        ),
    ]
